---
- name: Enable dwc2 overlay in config.txt
  lineinfile:
    path: /boot/firmware/config.txt
    line: "dtoverlay=dwc2"
    state: present

- name: Check if modules are already in cmdline.txt
  command: grep -q "modules-load=dwc2,g_ether" /boot/firmware/cmdline.txt
  register: modules_check
  failed_when: false
  changed_when: false

- name: Add modules to cmdline.txt if not present
  replace:
    path: /boot/firmware/cmdline.txt
    regexp: "(.*rootwait)(.*)$"
    replace: '\1 modules-load=dwc2,g_ether\2'
  when: modules_check.rc != 0

- name: Ensure g_ether module is loaded at boot
  lineinfile:
    path: /etc/modules
    line: "g_ether"
    state: present

- name: Load dwc2 module
  modprobe:
    name: dwc2
    state: present
  ignore_errors: true

- name: Load g_ether module
  modprobe:
    name: g_ether
    state: present
  ignore_errors: true

- name: Configure g_ether module options
  template:
    src: g_ether.conf.j2
    dest: "{{ modprobe_config.file }}"
    mode: "0644"
  notify: reload g_ether module

- name: Configure USB network interface
  template:
    src: usb0.network.j2
    dest: /etc/systemd/network/usb0.network
    mode: "0644"
  notify: restart networking

- name: Enable and start systemd-networkd
  systemd:
    name: systemd-networkd
    state: started
    enabled: true
    daemon_reload: true
