---
- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.d/99-ip-forward.conf

- name: Create udev rules for persistent interface names
  template:
    src: 70-persistent-net.rules.j2
    dest: /etc/udev/rules.d/70-persistent-net.rules
    mode: "0644"
  notify: reload udev rules

- name: Configure network interfaces
  template:
    src: "interface.network.j2"
    dest: "/etc/systemd/network/{{ item.value.name }}.network"
    mode: "0644"
  with_dict: "{{ interfaces }}"
  notify: restart networking

- name: Install iptables-persistent
  apt:
    name: iptables-persistent
    state: present
    update_cache: yes

- name: Configure NAT rules
  template:
    src: iptables-rules.j2
    dest: /etc/iptables/rules.v4
    mode: "0644"
  notify: reload iptables

- name: Enable and start systemd-networkd
  systemd:
    name: systemd-networkd
    state: started
    enabled: true
    daemon_reload: true
