- name: Build release binary
  become_user: proto
  shell: |
    export PKG_CONFIG_PATH="/usr/lib/arm-linux-gnueabihf/pkgconfig:/usr/share/pkgconfig"
    $HOME/.cargo/bin/cargo build --release --target=armv7-unknown-linux-gnueabihf
  args:
    chdir: /home/proto/protosuit-engine
    executable: /bin/bash
  when: "'hub' in group_names"
  register: build_result
  changed_when: build_result.rc == 0

- name: Deploy compiled binary
  copy:
    src: /home/proto/protosuit-engine/target/armv7-unknown-linux-gnueabihf/release/protosuit-engine-fin
    dest: /usr/local/bin/protosuit-engine-fin
    mode: "0755"
  when: "'fins' in group_names"

- name: Configure systemd service
  template:
    src: engine-fin.service.j2
    dest: /etc/systemd/system/engine-fin.service
  when: "'fins' in group_names"
  notify: restart engine fin

- name: Enable and start systemd service
  systemd:
    name: engine-fin
    enabled: yes
    state: started
  when: "'fins' in group_names"
