- name: Install ARM cross-compilation dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - libsdl2-dev
    - libx11-dev
    - libdbus-1-dev
    - libgl1-mesa-dev
    - libasound2-dev
  when: "'hub' in group_names"

- name: Set up Rust toolchain for user 'proto'
  become_user: proto
  shell: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    source $HOME/.cargo/env
    rustup target add arm-unknown-linux-gnueabihf
  args:
    creates: "/home/proto/.cargo/bin/rustup"
  when: "'hub' in group_names"
  changed_when: false

- name: Ensure .cargo directory exists
  file:
    path: /home/proto/.cargo
    state: directory
    owner: proto
    group: proto
    mode: "0755"
  when: "'hub' in group_names"

- name: Configure cargo environment for ARM target
  blockinfile:
    path: /home/proto/.cargo/config.toml
    create: yes
    owner: proto
    group: proto
    mode: "0644"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - ARM TARGET"
    block: |
      [target.arm-unknown-linux-gnueabihf]
      linker = "arm-linux-gnueabihf-gcc"
  when: "'hub' in group_names"

- name: Build release binary
  become_user: proto
  shell: |
    . $HOME/.cargo/env
    cargo build --release --target=arm-unknown-linux-gnueabihf
  args:
    chdir: /home/proto/protosuit-engine
    executable: /bin/bash
  when: "'hub' in group_names"
  register: build_result
  changed_when: build_result.rc == 0

- name: Install minimal runtime dependencies
  apt:
    name: libsdl2-2.0-0
    state: present
  when: "'fins' in group_names"

- name: Deploy compiled binary
  copy:
    src: /home/proto/protosuit-engine/target/arm-unknown-linux-gnueabihf/release/protosuit-engine-fin
    dest: /usr/local/bin/protosuit-engine-fin
    mode: "0755"
  when: "'fins' in group_names"

- name: Configure systemd service
  template:
    src: engine-fin.service.j2
    dest: /etc/systemd/system/engine-fin.service
  when: "'fins' in group_names"
  notify: restart engine fin

- name: Enable and start systemd service
  systemd:
    name: engine-fin
    enabled: yes
    state: started
  when: "'fins' in group_names"
