---
# Install common packages
- name: Install common tools
  apt:
    name:
      - zsh
      - git
      - htop
    state: present
    update_cache: yes

# Configure zsh
- name: Install Oh My Zsh
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "/home/proto/.oh-my-zsh"
    depth: 1
  become_user: proto

- name: Set zsh configuration
  ansible.builtin.copy:
    dest: "/home/proto/.zshrc"
    content: |
      export ZSH="/home/proto/.oh-my-zsh"
      ZSH_THEME="robbyrussell"

      # Show user@host in prompt
      PROMPT="%F{cyan}%n@%m%f $PROMPT"

      plugins=(git)
      source $ZSH/oh-my-zsh.sh
    owner: proto
    group: proto
    mode: "0644"

- name: Get zsh path
  command: which zsh
  register: zsh_path
  changed_when: false

- name: Change default shell to zsh
  command: chsh -s {{ zsh_path.stdout }} proto
  register: chsh_result
  changed_when: chsh_result.rc == 0
