---
- name: reboot system
  reboot:
    msg: "Rebooting to apply display rotation changes"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
  when: config_changes.changed or cmdline_changes.changed or enlightenment_install.changed or lightdm_config.changed

- name: set enlightenment permissions
  file:
    path: "{{ enlightenment_home }}/.elementary"
    owner: "{{ enlightenment_user }}"
    group: "{{ enlightenment_group }}"
    mode: "0755"
    recurse: yes
  when: enlightenment_check is succeeded or (enlightenment_check is failed and "not-installed" not in enlightenment_check.stdout)
