---
- name: reboot system
  reboot:
    msg: "Rebooting to apply display rotation changes"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
  when: config_changes.changed or cmdline_changes.changed
