---
- name: reload g_ether module
  shell:
    cmd: |
      modprobe -r g_ether
      modprobe g_ether
  ignore_errors: true

- name: restart networking
  systemd:
    name: systemd-networkd
    state: restarted
    daemon_reload: yes
