---
# First apply common setup to all hosts
- name: Configure common tools and shell
  hosts: all
  become: true
  roles:
    - common_setup

# Then configure networking
- name: Configure hub networking
  hosts: hub
  become: true
  roles:
    - hub_networking_setup

- name: Configure fin networking
  hosts: fins
  become: true
  roles:
    - fin_networking_setup
