---
- name: Configure networking
  import_playbook: networking.yml

- name: Configure displays
  import_playbook: display.yml

- name: Configure hub server
  import_playbook: hub_server.yml

- name: Configure Rust to compile Engine
  import_playbook: engine_build_config.yml

- name: Build and deploy Engine Fin
  import_playbook: build_deploy_fin_engine.yml
