---
- name: Configure networking
  import_playbook: networking.yml

- name: Configure displays
  import_playbook: display.yml

- name: Configure hub server
  import_playbook: hub_server.yml

- name: Build and deploy Engine Fin
  import_playbook: engine_fin.yml
