---
# Install minimal X server and Matchbox dependencies
- name: Install X server and Matchbox Window Manager
  apt:
    name:
      - xserver-xorg-core
      - xserver-xorg-input-all
      - xinit
      - matchbox-window-manager
    state: present
    update_cache: yes

# Configure X server with rotation
- name: Configure X server with display rotation
  template:
    src: xorg.conf.j2
    dest: /etc/X11/xorg.conf
    mode: "0644"
  notify: restart matchbox

# Configure autostart for Matchbox
- name: Create Matchbox autostart directory
  file:
    path: /etc/X11/matchbox
    state: directory
    mode: "0755"

- name: Configure Matchbox autostart
  template:
    src: autostart.sh.j2
    dest: /etc/X11/matchbox/autostart.sh
    mode: "0755"
  notify: restart matchbox

# Configure .xinitrc for the proto user
- name: Create .xinitrc file
  template:
    src: xinitrc.j2
    dest: /home/proto/.xinitrc
    mode: "0644"
    owner: proto
    group: proto
  notify: restart matchbox

# Configure X.Org permissions
- name: Add proto user to tty group
  user:
    name: proto
    groups: tty
    append: yes

- name: Configure X.Org to allow users in tty group
  copy:
    dest: /etc/X11/Xwrapper.config
    content: |
      allowed_users=anybody
      needs_root_rights=yes
    mode: "0644"
  notify: restart matchbox

# Configure systemd service for X server with Matchbox
- name: Update matchbox service to run as proto user
  template:
    src: matchbox.service.j2
    dest: /etc/systemd/system/matchbox.service
    mode: "0644"
  notify: restart matchbox

# Enable and start the service
- name: Enable and start Matchbox service
  systemd:
    name: matchbox
    state: started
    enabled: true
    daemon_reload: true

# Disable screen blanking
- name: Disable screen blanking in X
  lineinfile:
    path: /etc/X11/xorg.conf
    line: '    Option "BlankTime" "0"'
    insertafter: 'Section "ServerFlags"'
    create: yes
