---
# Install minimal X server and Matchbox dependencies
- name: Install X server and Matchbox Window Manager
  apt:
    name:
      - xserver-xorg-core
      - xserver-xorg-input-all
      - xinit
      - matchbox-window-manager
    state: present
    update_cache: yes

# Disable unnecessary X server features
- name: Create custom X server configuration
  template:
    src: xorg.conf.j2
    dest: /etc/X11/xorg.conf
    mode: "0644"

# Configure autostart for Matchbox
- name: Create Matchbox autostart directory
  file:
    path: /etc/X11/matchbox
    state: directory
    mode: "0755"

- name: Configure Matchbox autostart
  template:
    src: autostart.sh.j2
    dest: /etc/X11/matchbox/autostart.sh
    mode: "0755"

# Configure .xinitrc for the proto user
- name: Create .xinitrc file
  template:
    src: xinitrc.j2
    dest: /home/proto/.xinitrc
    mode: "0644"
    owner: proto
    group: proto

# Configure X.Org permissions
- name: Add proto user to tty group
  user:
    name: proto
    groups: tty
    append: yes

- name: Configure X.Org to allow users in tty group
  copy:
    dest: /etc/X11/Xwrapper.config
    content: |
      allowed_users=anybody
      needs_root_rights=yes
    mode: "0644"

# Configure systemd service for X server with Matchbox
- name: Update matchbox service to run as proto user
  template:
    src: matchbox.service.j2
    dest: /etc/systemd/system/matchbox.service
    mode: "0644"

# Enable the service
- name: Enable and start Matchbox service
  systemd:
    name: matchbox
    state: started
    enabled: true
    daemon_reload: true
  notify: restart matchbox

# Configure display rotation in config.txt
- name: Configure display rotation
  lineinfile:
    path: /boot/firmware/config.txt
    regexp: "^display_rotate="
    line: "{% if inventory_hostname == 'left_fin' %}display_rotate=3{% elif inventory_hostname == 'right_fin' %}display_rotate=1{% endif %}" # 3=270 degrees, 1=90 degrees
  register: rotation_config
  notify: reboot system
  when: "'fins' in group_names"
