---
# Install minimal X server and Matchbox dependencies
- name: Install X server and Matchbox Window Manager
  apt:
    name:
      - xserver-xorg-core
      - xserver-xorg-input-all
      - xinit
      - matchbox-window-manager
    state: present
    update_cache: yes

# Disable unnecessary X server features
- name: Create custom X server configuration
  template:
    src: xorg.conf.j2
    dest: /etc/X11/xorg.conf
    mode: "0644"

# Configure autostart for Matchbox
- name: Create Matchbox autostart directory
  file:
    path: /etc/X11/matchbox
    state: directory
    mode: "0755"

- name: Configure Matchbox autostart
  template:
    src: autostart.sh.j2
    dest: /etc/X11/matchbox/autostart.sh
    mode: "0755"

# Configure .xinitrc for the proto user
- name: Create .xinitrc file
  template:
    src: xinitrc.j2
    dest: /home/proto/.xinitrc
    mode: "0644"
    owner: proto
    group: proto

# Configure X.Org permissions
- name: Add proto user to tty group
  user:
    name: proto
    groups: tty
    append: yes

- name: Configure X.Org to allow users in tty group
  copy:
    dest: /etc/X11/Xwrapper.config
    content: |
      allowed_users=anybody
      needs_root_rights=yes
    mode: "0644"

# Configure systemd service for X server with Matchbox
- name: Update matchbox service to run as proto user
  template:
    src: matchbox.service.j2
    dest: /etc/systemd/system/matchbox.service
    mode: "0644"

# Enable the service
- name: Enable and start Matchbox service
  systemd:
    name: matchbox
    state: started
    enabled: true
    daemon_reload: true
  notify: restart matchbox

# Configure display settings in config.txt
- name: Ensure display configuration exists
  blockinfile:
    path: /boot/firmware/config.txt
    block: |
      # Display configuration
      hdmi_force_hotplug=1
      hdmi_group=2
      hdmi_mode=87
      hdmi_cvt 720 720 60 1 0 0 0
      {% if inventory_hostname == 'left_fin' %}
      display_rotate=3  # 270 degrees rotation
      {% elif inventory_hostname == 'right_fin' %}
      display_rotate=1  # 90 degrees rotation
      {% endif %}
    marker: "# {mark} ANSIBLE MANAGED BLOCK - DISPLAY CONFIG"
  register: config_changes
  notify: reboot system
  when: "'fins' in group_names"

# Configure kernel parameters in cmdline.txt
- name: Configure display rotation in cmdline.txt
  lineinfile:
    path: /boot/firmware/cmdline.txt
    regexp: "video=HDMI-A-1:"
    line: '{{ lookup("file", "/boot/firmware/cmdline.txt") | regex_replace("$", "") }}{% if inventory_hostname == "left_fin" %} video=HDMI-A-1:720x720@60,rotate=270{% elif inventory_hostname == "right_fin" %} video=HDMI-A-1:720x720@60,rotate=90{% endif %}'
    backrefs: yes
  register: cmdline_changes
  notify: reboot system
  when: "'fins' in group_names"
