---
# Install minimal X server
- name: Install X server
  apt:
    name:
      - xserver-xorg-core
      - xserver-xorg-input-all
    state: present
    update_cache: yes

# Disable unnecessary X server features
- name: Create custom X server configuration
  template:
    src: xorg.conf.j2
    dest: /etc/X11/xorg.conf
    mode: "0644"

# Configure X.Org permissions
- name: Add proto user to tty group
  user:
    name: proto
    groups: tty
    append: yes

- name: Configure X.Org to allow users in tty group
  copy:
    dest: /etc/X11/Xwrapper.config
    content: |
      allowed_users=anybody
      needs_root_rights=yes
    mode: "0644"

# Configure display settings in config.txt
- name: Ensure display configuration exists
  blockinfile:
    path: /boot/firmware/config.txt
    block: |
      # Display configuration
      hdmi_force_hotplug=1
      hdmi_group=2
      hdmi_mode=87
      hdmi_cvt 720 720 60 1 0 0 0
      video=HDMI-A-1:720x720@60
    marker: "# {mark} ANSIBLE MANAGED BLOCK - DISPLAY CONFIG"
  register: config_changes
  when: "'fins' in group_names"
